[package]
name = "gridiron-mocks"
version = "0.2.0"
authors = ["Gridiron"]
edition = "2021"
description = "Mock Gridiron contracts used for integration testing"
license = "GPL-3.0-only"
repository = "https://github.com/gridironzone/gridiron-core"
homepage = "https://gridiron.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gridiron = { path = "../gridiron" }
gridiron-factory = { path = "../../contracts/factory" }
gridiron-generator = { path = "../../contracts/tokenomics/generator" }
gridiron-native-coin-registry = { path = "../../contracts/periphery/native_coin_registry" }
gridiron-shared-multisig = { path = "../../contracts/periphery/shared_multisig" }
gridiron-pair = { path = "../../contracts/pair" }
gridiron-pair-stable = { path = "../../contracts/pair_stable" }
gridiron-pair-concentrated = { path = "../../contracts/pair_concentrated" }
gridiron-staking = { path = "../../contracts/tokenomics/staking" }
gridiron-token = { path = "../../contracts/token" }
gridiron-vesting = { path = "../../contracts/tokenomics/vesting" }
gridiron-whitelist = { path = "../../contracts/whitelist" }
gridiron-xgrid-token = { path = "../../contracts/tokenomics/xgrid_token" }
cosmwasm-schema = "1.2.5"
cosmwasm-std = "1.2.5"
cw-multi-test = { git = "https://github.com/gridironzone/cw-multi-test.git", rev = "269a2c829d1ad25d67caa4600f72d2a21fb8fdeb" }
injective-cosmwasm = "0.2"
schemars = "0.8.1"
serde = "1.0"
cw-utils = "1.0"
cw20 = "0.15"
anyhow = "1.0"
cw3 = "1.0"
